const state = {
  account: {
    account_blocked: false,
    account_number: '',
    buying_power: '',
    cash: '',
    created_at: '',
    currency: '',
    daytrade_count: 0,
    daytrading_buying_power: '',
    equity: '',
    id: '',
    initial_margin: '',
    last_equity: '',
    last_maintenance_margin: '',
    long_market_value: '',
    maintenance_margin: '',
    multiplier: '',
    pattern_day_trader: false,
    portfolio_value: '',
    regt_buying_power: '',
    short_market_value: '',
    shorting_enabled: false,
    sma: '',
    status: '',
    trade_suspended_by_user: false,
    trading_blocked: false,
    transfers_blocked: false,
  },
  app: {
    buyOrders: [],
    buyTotal: 0,
    buys: 0,
    graphData: [],
    positions: [],
    profit: 0,
    profitData: {},
    sellOrders: [],
    sellTotal: 0,
    sells: 0,
    status: 'LOADING',
    ticks: 0,
    updated: null,
  },
  clock: {
    is_open: false,
    next_close: '',
    next_open: '',
    timestamp: '',
  },
  history: {},
  quotes: {},
};

export default state;
